version: '3.9'

services:
  php:
    build: ./infra/php
    volumes:
      - ./backend:/work

  nginx:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/:/etc/nginx/conf.d/
    working_dir: /work

  mysql:
    build: ./infra/mysql
    ports:
      - 33306:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: